Write a program that takes an array $A$ and an index $i$ into $A$, and rearranges the elements such that all elements less than $A[i]$ (the pivot) appear first, followed by elements equal to the pivot, followed by elements greater than the pivot.

In [1]:
def swap(i,j,A):
    """
    Swap the element i and j of an array A
    """
    temp = A[i]
    A[i] = A[j]
    A[j] = temp

In [40]:
def DutchFlagPartition(pivot_index, A):
    """
    Keep the following invariants during partitioning:
    bottom group:       A[0:smaller-1]
    middle group:       A[smaller:equal-1]
    unclassified group: A[equal:larger]
    top group:          A[larger+1:]
    """
    
    pivot = A[pivot_index]
    
    smaller = 0
    equal = 0
    larger = len(A)-1
    
    # Keep iterating until there is no unclassified element
    while equal <= larger:
        print("-------------")
        print(smaller, equal, larger)
        if A[equal] < pivot:
            swap(equal, smaller, A)
            equal += 1
            smaller += 1
        elif A[equal] == pivot:
            equal += 1
        else:
            swap(equal, larger, A)
            larger -= 1
        print(A)
        print(smaller, equal, larger)
            
    return A

In [50]:
import numpy as np
A = np.random.randint(10, size=8)
print(A)
print("-------------")
pivot_index = 3
print("pivot = ", A[pivot_index])
DutchFlagPartition(pivot_index, A)

[4 0 2 3 6 9 0 9]
-------------
pivot =  3
-------------
0 0 7
[9 0 2 3 6 9 0 4]
0 0 6
-------------
0 0 6
[0 0 2 3 6 9 9 4]
0 0 5
-------------
0 0 5
[0 0 2 3 6 9 9 4]
1 1 5
-------------
1 1 5
[0 0 2 3 6 9 9 4]
2 2 5
-------------
2 2 5
[0 0 2 3 6 9 9 4]
3 3 5
-------------
3 3 5
[0 0 2 3 6 9 9 4]
3 4 5
-------------
3 4 5
[0 0 2 3 9 6 9 4]
3 4 4
-------------
3 4 4
[0 0 2 3 9 6 9 4]
3 4 3


array([0, 0, 2, 3, 9, 6, 9, 4])